databaseChangeLog:
  - changeSet:
      id: 3.6.0
      author: GraviteeSource Team
      changes:

        # Flows
        ###############
        - addColumn:
            tableName: flows
            columns:
              - column: {name: application_id, type: nvarchar(64), constraints: { nullable: true } }
        - createIndex:
            columns:
              - column:
                  name: reference_id
              - column:
                  name: reference_type
              - column:
                  name: application_id
            indexName: idx_flow_by_application
            tableName: flows
            unique: false

        # Authentication Context
        ########################
        - createTable:
            tableName: authentication_contexts
            columns:
              - column: { name: id, type: nvarchar(138), constraints: { nullable: false } }
              - column: { name: session_id, type: nvarchar(128), constraints: { nullable: true } }
              - column: { name: version, type: int, constraints: { nullable: true } }
              - column: { name: created_at, type: timestamp(6), constraints: { nullable: true } }
              - column: { name: expire_at, type: timestamp(6), constraints: { nullable: true } }
              - column: { name: data, type: clob, constraints: { nullable: true } }

        - sql:
            dbms: postgresql
            sql: ALTER TABLE authentication_contexts ALTER data TYPE JSON USING data::json

        - sql:
            dbms: mysql
            sql: ALTER TABLE authentication_contexts MODIFY data JSON;

        - addPrimaryKey:
            constraintName: pk_authentication_contexts
            columnNames: id
            tableName: authentication_contexts

        - createIndex:
            columns:
              - column:
                  name: session_id
              - column:
                  name: version
            indexName: idx_authentication_contexts_session_version
            tableName: authentication_contexts
            unique: true
